<?php

namespace PR2\PokemonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BasePokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePokemonRepository extends EntityRepository
{
}
