<?php

namespace PR2\PokemonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BasePokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePokemonRepository extends EntityRepository
{
    public function searchByPagination($search, $limit = 0, $offset = 0)
    {
        $qb = $this->createQueryBuilder();

        if ($limit) {
            $qb->setMaxResults( $limit );
        }

        if ($offset) {
            $qb->setFirstResult( $offset );
        }

        return $qb->getQuery()->getResult();
    }
}
