<?php

namespace PR2\PokemonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PokemonSauvageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonSauvageRepository extends EntityRepository
{
}
