pr2_core:
    resource: "@PR2CoreBundle/Resources/config/routing.yml"
    prefix:   /

pr2_settings:
    resource: "@PR2SettingsBundle/Resources/config/routing.yml"
    prefix:   /

pr2_pokemon:
    resource: "@PR2PokemonBundle/Resources/config/routing.yml"
    prefix:   /

pr2_forum:
    resource: "@PR2ForumBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    pattern:   /login
    defaults:  { _controller: PR2CoreBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout