security:
    encoders:
        PR2\ForumBundle\Entity\Membre: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_MEMBRE, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: PR2\ForumBundle\Entity\Membre, property: identifiant }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_MEMBRE' ] }
                    mod:  { password: modpass, roles: [ 'ROLE_MODERATEUR' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /forum
            logout:
                path: logout
                target: /forum

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
