pr2_settings_homepage:
    pattern:  /setting/
    defaults: { _controller: PR2SettingsBundle:Setting:index }

pr2_settings_theme:
    pattern:  /setting/theme/
    defaults: { _controller: "PR2SettingsBundle:Theme:index" }

pr2_settings_theme_show:
    pattern:  /setting/theme/voir/{id}
    defaults: { _controller: "PR2SettingsBundle:Theme:show" }

pr2_settings_theme_new:
    pattern:  /setting/theme/ajouter
    defaults: { _controller: "PR2SettingsBundle:Theme:ajouter" }

pr2_settings_theme_edit:
    pattern:  /setting/theme/modifier/{id}
    defaults: { _controller: "PR2SettingsBundle:Theme:modifier" }

pr2_settings_theme_delete:
    pattern:  /setting/theme/supprimer/{id}
    defaults: { _controller: "PR2SettingsBundle:Theme:supprimer" }