<?php

namespace PR2\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DresseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DresseurRepository extends EntityRepository
{
}
