pr2membre_index:
    path: /administration/membre
    defaults: { _controller: PR2CoreBundle:Membre:index }

pr2membre_voir:
    path: /administration/membre/voir/{id}
    defaults: { _controller: PR2CoreBundle:Membre:voir }
    requirements:
        id:  \d+

pr2membre_ajouter:
    path: /administration/membre/ajouter
    defaults:  { _controller: PR2CoreBundle:Membre:ajouter }

pr2membre_modifier:
    path: /administration/membre/modifier/{id}
    defaults:  { _controller: PR2CoreBundle:Membre:modifier }
    requirements:
        id:  \d+

pr2membre_supprimer:
    path: /administration/membre/supprimer/{id}
    defaults:  { _controller: PR2CoreBundle:Membre:supprimer }
    requirements:
        id:  \d+
