pr2forum_accueil:
    pattern:  /forum
    defaults: { _controller: PR2ForumBundle:Forum:index }

pr2forum_statistique:
    pattern:  /forum/statistiques
    defaults: { _controller: PR2ForumBundle:Forum:statistique }

pr2forum_voirMembres:
    pattern:  /forum/membre
    defaults: { _controller: PR2ForumBundle:Forum:voirMembres }

pr2forum_voirRegion:
    path: /forum/region/{id}
    defaults:  { _controller: PR2ForumBundle:Forum:voirRegion }

pr2forum_voirLieu:
    path: /forum/lieu/{id}
    defaults:  { _controller: PR2ForumBundle:Forum:voirLieu }

pr2forum_voirSujet:
    path: /forum/sujet/{id}
    defaults:  { _controller: PR2ForumBundle:Forum:voirSujet }

pr2admin_index:
    pattern: /administration
    defaults: { _controller: PR2ForumBundle:Admin:index}

pr2region_index:
    path: /administration/region
    defaults: { _controller: PR2ForumBundle:Region:index }

pr2region_voir:
    path: /administration/region/voir/{id}
    defaults: { _controller: PR2ForumBundle:Region:voir }
    requirements:
        id:  \d+

pr2region_ajouter:
    path: /administration/region/ajouter
    defaults:  { _controller: PR2ForumBundle:Region:ajouter }

pr2region_modifier:
    path: /administration/region/modifier/{id}
    defaults:  { _controller: PR2ForumBundle:Region:modifier }
    requirements:
        id:  \d+

pr2region_supprimer:
    path: /administration/region/supprimer/{id}
    defaults:  { _controller: PR2ForumBundle:Region:supprimer }
    requirements:
        id:  \d+

pr2lieu_index:
    path: /administration/lieu
    defaults: { _controller: PR2ForumBundle:Lieu:index }

pr2lieu_voir:
    path: /administration/lieu/voir/{id}
    defaults: { _controller: PR2ForumBundle:Lieu:voir }
    requirements:
        id:  \d+

pr2lieu_ajouter:
    path: /administration/lieu/ajouter
    defaults:  { _controller: PR2ForumBundle:Lieu:ajouter }

pr2lieu_modifier:
    path: /administration/lieu/modifier/{id}
    defaults:  { _controller: PR2ForumBundle:Lieu:modifier }
    requirements:
        id:  \d+

pr2lieu_supprimer:
    path: /administration/lieu/supprimer/{id}
    defaults:  { _controller: PR2ForumBundle:Lieu:supprimer }
    requirements:
        id:  \d+

pr2tuile_index:
    path: /administration/region/carte/{id}/{selection}
    defaults: { _controller: PR2ForumBundle:Tuile:index }
    requirements:
        id:  \d+
        selection: \d+

pr2tuile_ajouter:
    path: /administration/region/carte/ajouter/{id}/{direction}
    defaults: { _controller: PR2ForumBundle:Tuile:ajouter }
    requirements:
        id:  \d+
        direction: \d+

pr2tuile_supprimer:
    path: /administration/region/carte/supprimer/{id}/{direction}
    defaults: { _controller: PR2ForumBundle:Tuile:supprimer }
    requirements:
        id:  \d+
        direction: \d+

pr2sujet_index:
    path: /administration/sujet
    defaults: { _controller: PR2ForumBundle:Sujet:index }

pr2sujet_voir:
    path: /administration/sujet/voir/{id}
    defaults: { _controller: PR2ForumBundle:Sujet:voir }
    requirements:
        id:  \d+

pr2sujet_ajouter:
    path: /forum/ajouter/sujet/{lieu}
    defaults:  { _controller: PR2ForumBundle:Sujet:ajouter }
    requirements:
        lieu:  \d+

pr2sujet_modifier:
    path: /administration/sujet/modifier/{id}
    defaults:  { _controller: PR2ForumBundle:Sujet:modifier }
    requirements:
        id:  \d+

pr2sujet_supprimer:
    path: /administration/sujet/supprimer/{id}
    defaults:  { _controller: PR2ForumBundle:Sujet:supprimer }
    requirements:
        id:  \d+

pr2dresseur_index:
    path: /forum/dresseur
    defaults: { _controller: PR2ForumBundle:Dresseur:index }

pr2dresseur_voir:
    path: /forum/dresseur/{id}
    defaults: { _controller: PR2ForumBundle:Dresseur:voir }
    requirements:
        id:  \d+

pr2dresseur_journal:
    path: /forum/dresseur/journal/{id}
    defaults: { _controller: PR2ForumBundle:Dresseur:journal }
    requirements:
        id:  \d+